### ISSUE TITLE
Module 1.3: adding Spacy check at runtime

### ISSUE THREAD

**Issue by basaldella** [cambridgeltl/python4cl#9]
In module 1.3, where we ask students to install spacy, we could do it directly in the notebook - we could just prepare a cell with the content

```
!python -m spacy download en_core_web_sm
```
And ask them to check that the instruction prints ```✔ Download and installation successful```. It's less challenging than asking them to use a terminal and/or to know how to deal with pip.

**Comment by zhu-y11** [comment]
Added
